In [4]:
import numpy as np

In [7]:
liste1 = [[1,2,3,4],[1,2,3]]

In [17]:
t = 0
for i in range(len(liste1)):
    t += len(liste1[i])
print(t)

7


In [23]:
arr = np.array([[1,2,3],[4,5,6]],dtype="int")

In [25]:
arr.astype("str")

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U21')

In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a*b,"\n")
print(np.dot(a,b))

[ 4 10 18] 

32


In [42]:
matrix = np.array([ [1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9] ])

matrix[0:2, 0:1]
#cevap: 2, 2, 8, hata

array([[1],
       [4]])

In [ ]:
for i in range(10)

In [ ]:
liste1 =([  [1, 2, 3], 
            [4, 5, 6], 
            [7, 8, 9] ])

In [38]:
liste1[1][1]

5

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])

print(a + b)

#[[11,22],[13,24]]

[[11 22]
 [13 24]]


In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr % 2 == 0)

[False  True False  True]


In [51]:
arr = np.arange(6)
print(arr, "\n")
print(arr.reshape(2,3),"\n")
print(arr.reshape(6,1),"\n")

[0 1 2 3 4 5] 

[[0 1 2]
 [3 4 5]] 

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] 



In [ ]:
print(np.random.rand(3,4),"\n") # 0 ile 1 arasında 3 satır 4 sütunluk rastgele değer üretir. Eşit olasılık.
print(np.random.randn(2,5)) # 0 ile 1 arasında ort=0, std=1 olacak şekilde normal dağılım olacak şekilde rastgele sayı üretir.
print(np.random.randint(1,50,15), "\n") # 1 ile 50 arasında rastgele 15 tane sayı üretir.

In [57]:
np.random.rand(3,2)

array([[0.35892815, 0.07844604],
       [0.2920642 , 0.70273794],
       [0.19277416, 0.40354685]])

In [58]:
np.random.rand(3)

array([0.96844003, 0.96288906, 0.33482081])

In [59]:
np.random.randn(2)

array([ 2.33282893, -0.86692772])

In [62]:
#1. Elemanları [1, 2, 3, 4, 5] olan bir NumPy dizisi nasıl oluşturulur?
np.arange(6)
liste1 = np.array([1, 2, 3, 4, 5])
liste1

array([1, 2, 3, 4, 5])

In [ ]:
#2 satır ve 3 sütundan oluşan, tüm elemanları 0 olan bir NumPy dizisi nasıl oluşturulur?

In [66]:
np.zeros((2,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
#3. Bir NumPy dizisinin boyutlarını (shape) nasıl öğrenirsiniz?

In [71]:
liste1 = np.array([1, 2, 3, 4, 5])
liste1.shape

(5,)

In [72]:
#4. Bir NumPy dizisinin elemanlarının veri tipini (dtype) nasıl öğrenirsiniz?
liste1.dtype

dtype('int64')

In [ ]:
#5. a = np.array([1, 2, 3]) ve b = np.array([4, 5, 6]) dizileri verildiğinde, bu iki dizinin eleman bazında toplamını nasıl bulursunuz?

In [73]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a+b

array([5, 7, 9])

In [ ]:
#6. arr = np.array([10, 20, 30, 40, 50]) dizisinin ortalamasını nasıl hesaplarsınız?

In [86]:
arr = np.array([10, 20, 30, 40, 50])
arr.mean(dtype=int)

np.int64(30)

In [ ]:
#7. arr = np.array([1, 2, 3, 4, 5, 6]) dizisini 2 satır ve 3 sütunluk bir diziye nasıl yeniden şekillendirirsiniz

In [88]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
#arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) dizisinden 3 ile 7 arasındaki (7 dahil değil) elemanları nasıl seçersiniz (slicing)?

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
arr[3:7]

array([3, 4, 5, 6])

In [93]:
#9. Elemanları 1'den 10'a kadar (10 dahil) olan bir NumPy dizisi nasıl oluşturulur?
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#1. arr = np.array([1, 5, 2, 7, 3, 8, 4, 6]) dizisi verildiğinde, 5'ten büyük olan elemanları boolean indeksleme (boolean indexing) kullanarak nasıl seçersiniz?

In [94]:
arr=np.array([1,5,2,7,3,8,4,6])
arr>5

array([False, False, False,  True, False,  True, False,  True])

In [105]:
liste=[1,5,2,7,3,8,4,6]
sonuc=[]
for i in (liste):
    if i>5:
        sonuc.append(True)
    else:
        sonuc.append(False)
print(sonuc)

[False, False, False, True, False, True, False, True]


In [ ]:
#2. A = np.array([[1, 2], [3, 4]]) ve B = np.array([[5, 6], [7, 8]]) matrisleri verildiğinde, bu iki matrisin çarpımını (matris çarpımı) nasıl hesaplarsınız?

In [108]:
A = np.array([[1, 2], [3, 4]]) 
B = np.array([[5, 6], [7, 8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [109]:
A@B

array([[19, 22],
       [43, 50]])

In [ ]:
#3. arr = np.array([1, 2, 2, 3, 4, 4, 4, 5, 5]) dizisindeki benzersiz (unique) elemanları ve bu elemanların kaçar kez tekrarlandığını nasıl bulursunuz?

In [ ]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5, 5])
print(np.unique(arr))
print(np.unique_counts(arr))

benzersizler, sayisi =  np.unique(arr,return_counts=True)
print(benzersizler, sayisi)


[1 2 3 4 5]
UniqueCountsResult(values=array([1, 2, 3, 4, 5]), counts=array([1, 2, 1, 3, 2]))
[1 2 3 4 5] [1 2 1 3 2]


In [139]:
liste =np.array( ["zeynep", "şevval", "Özgür"])

def sec():
    rand = np.random.randint(1,101)
    sec = ""
    if rand <= 90:
        sec = "Gulay"
        return sec, rand
    else:
        sec = np.random.choice(liste)
        return sec, rand

In [166]:
sec()

('Gulay', 81)