# Numpy

* Python'da bilimsel hesaplamalar ve veri analizi için temel kütüphanedir. 
* **Yüksek performanslı çok boyutlu diziler (arrays)** vu bu diziler üzerinde işlemler yapmamızı sağlar

In [ ]:
import numpy as np

### 1.1 Numpy Dizisi (Array) Oluşturma

* Temel liste ve numpy listesi

In [8]:
liste1 = [1,2,3]
#liste2 = np.array([4,5,6]) # 1 boyutlu (vektör)
liste2 = np.array([4,5,6])
liste3 = np.array(liste1)
liste4 = np.array([[1,2,3],[4,5,6]]) 

print(type(liste1))
print(type(liste2))
print(type(liste3))
print(type(liste4))

<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [14]:
# 0'lardan oluşan matris
print(np.zeros(5),"\n") # tek boyutlu

print(np.zeros((3,4))) # iki boyutlu
np.zeros((2,5))

[0. 0. 0. 0. 0.] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
# 1'lerden oluşan matris
print(np.ones(2), "\n") # tek boyutlu
np.ones(4)

print(np.ones((5,3))) # iki boyutlu


[1. 1.] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
# 5'lerden oluşan bir matris oluşturalım.

n = np.ones((2,3)) + 5
print(n)
n[1][1]
print(type(n[0] [0]))

[[6. 6. 6.]
 [6. 6. 6.]]
<class 'numpy.float64'>


In [31]:
x = 3.4
type(x)

float

In [36]:
def hesapla(x, y=2):
    print(x + y)

In [38]:
hesapla(3, 4.6)

7.6


In [39]:
# birim matris

np.eye(3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# numpy'a özgü range fonksiyonu
print(np.arange(20)) # 0,1,2,3,...,19
print(np.arange(1,10)) # 1'den başla 10'a kadar git.
print(np.arange(1,10,2)) # 1'den başla 10'a kadar git ve 2 atlayarak devam et.
print(np.arange(1,5, 0.3)) # 1'den 5'e kadar 0.3 atlayarak ilerle
np.arange()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[1.  1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4.  4.3 4.6 4.9]


In [42]:
# eşit aralıklardan oluşan bir dizi oluşturalım.

print(np.linspace(1,5,3)) # 1 ile 5 arasında eşit aralıklı 3 sayı 
print(np.linspace(0,1,5)) # 0 ile 1 arasında eşit aralıklı 5 sayı 

[1. 3. 5.]
[0.   0.25 0.5  0.75 1.  ]


### 1.2 Dizi Özellikleri

In [ ]:
liste2 = np.array([4,5,6])
liste4 = np.array([[1,2,3],
                   [4,5,6]]) 

In [130]:
print(liste2.shape)  # dizinin kaç satır kaç sütundan oluştuğu bilgisini verir.
liste4.ndim # dizinin kaç boyutlu olduğunu verir.(dimension)
liste2.size # dizinin kaç elemanlı olduğunu verir
liste4.size
liste2.dtype # elemanların veri tipini verir
liste4.dtype
liste2.nbytes # Dizinin bellekte kapladığı toplam alan (byte cinsinden)
liste4.nbytes
liste2.T # Dizinin transpozu
liste4.T
liste4.flatten() # çok boyutlu diziyi tek boyutlu diziye indirir.
liste2.astype(str) # Veri tipini değiştirir. (float, int, str)

(3,)


array(['4', '5', '6'], dtype='<U21')

## 2. Dizi İşlemleri

### 2.1 Matematiksel İşlemler

In [78]:
liste1 = [1, 2, 3]
liste2 = [4, 5, 6]
for i in range(len(liste1)):
    print(liste1[i]+liste2[i])

5
7
9


In [79]:
arr1 = np.array(liste1)
arr2 = np.array(liste2)

In [89]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(liste1 + liste2)
print(arr1 + arr2)
print(arr1 * 5)
#print(arr2 / 2)
print( np.dot(arr1, arr2)) # iç çarpım: 1*4 + 2*5 + 3*6 = 32
print( arr1 > 2)


[1, 2, 3, 4, 5, 6]
[5 7 9]
[ 5 10 15]
32
[False False  True]


### 2.2 İndeksleme ve Dilimleme

In [93]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
a[2]

np.int64(4)

In [95]:
a[::2]

array([0, 2, 4, 6, 8])

In [96]:
matrix = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])

In [98]:
matrix[2][1]
print(matrix[1, 2]) # 6 (2.satır, 3.sütun)
#print(matrix[:, 0]) # Tüm satırların birinci sütunu
#print(matrix[0:2, 1:3]) # [[2, 3], [5, 6]] --> 0 ile 1. satır arasından, 1 ile 2. sütunlarından değerlerini getirir.

6


In [118]:
np.sin(90)

np.float64(0.8939966636005579)

### 2.3 Broadcasting

Farklı boyutlu dizileri işleme alma:

In [119]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
print(a + b)  # Burada b matrisi otomatik olarak genişledi yani [[10, 20], [10,20]] şekline geldi.

[[11 22]
 [13 24]]


## 3. Matematiksel Fonksiyonlar

In [ ]:
arr = np.array([1, 2, 3, 4])

print(np.sum(arr)) # 10 --> elemanların toplamı
print(np.mean(arr)) # arr dizisinin ortalaması
print(np.std(arr)) # standart sapması
print(np.var(arr)) # varyans
print(np.median(arr)) # median
print(np.sin(arr)) # sinüs değerleri
print(np.log(arr)) # Doğal logaritması
print(np.unique(arr)) # Dizinin içersini benzersiz değerlere dönüştürür. (1,1,1,2,3,4,5,5) -> (1,2,3,4,5)
print(np.sqrt(arr)) # karekök alma
print(arr % 2 == 0) # arr dizisindeki her bir elemanın 2'ye bölünüp bölünmediğini kontrol ediyor.

10
2.5
1.118033988749895
1.25
2.5
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[False  True False  True]


## 4. Dizi Manipülasyonu

In [140]:
# Yeniden şekillendirme
arr = np.arange(6)  # [[0,1,2], [3,4,5]]

# Birleştirme
a = np.array([1, 2])
b = np.array([3, 4])
#concat = np.concatenate((a, b))  # [1,2,3,4]

# Split
parcalar = np.split(arr, 3)  # İki parçaya ayırır
print(parcalar)


[array([0, 1]), array([2, 3]), array([4, 5])]


In [131]:
a = np.array([1, 2])
b = np.array([3, 4])
a+b

array([4, 6])

## 5. Rastgele Sayı Üretme

In [160]:
#print(np.random.rand(3,4),"\n") # 0 ile 1 arasında 3 satır 4 sütunluk rastgele değer üretir. Eşit olasılık.

#print(np.random.randn(2,5)) # 0 ile 1 arasında ort=0, std=1 olacak şekilde normal dağılım olacak şekilde rastgele sayı üretir.

print(np.random.randint(1,50,15), "\n") # 1 ile 50 arasında rastgele 15 tane sayı üretir.


[48 37 10 24 21  6 49 12 36 25 24 27 26 29 11] 



In [163]:
import time

# Veri boyutu
N = 10**7

# Python listeleri
liste1 = list(range(N))
liste2 = list(range(N))

# NumPy dizileri
numpy_dizi1 = np.array(liste1)
numpy_dizi2 = np.array(liste2)

# Python listesi ile toplama
start = time.time()
toplam = [x + y for x, y in zip(liste1, liste2)]
print("Python:", time.time() - start, "saniye")

# NumPy ile toplama
start = time.time()
toplam = numpy_dizi1 + numpy_dizi2
print("NumPy:", time.time() - start, "saniye")

Python: 1.5845441818237305 saniye
NumPy: 0.45421266555786133 saniye


False